### PR TITLE
Update memoist

### PR DESCRIPTION
**Pull request by cmckni3**

### CODE REVIEW

**Comment by cmckni3** [comment]
Huh I guess the master branch was protected.

**Comment by cmckni3** [comment]
ping @midwire

**Comment by etbender** [comment]
Can you please publish this change to RubyGems.org?

**Comment by WesUnwin** [comment]
Would be great if the change to make this library use the new memoist were released, looks like it was merged months ago though

**Comment by cmckni3** [comment]
0.3.0 published to [rubygems](https://rubygems.org/gems/my_zipcode_gem/versions/0.3.0)

**Pull request merged**
