### PR TITLE
Zipcode references

### PR DESCRIPTION
**Pull request by akoinesjr**
Adds a method to find all zip codes by city and states in addition to just the first.

### CODE REVIEW

**Comment by akoinesjr** [comment]
@cmckni3 Thanks for the quick fix! A `find_all` was useful for my use case, figured I'd submit a little PR using yours as a base!

**Comment by cmckni3** [comment]
Thanks!

**Comment by cmckni3** [comment]
Let me see if I have Rubygems access.

**Comment by cmckni3** [comment]
Created an issue to create a new release since I don't have access.

**Comment by cmckni3** [comment]
Released in 0.2.2 @akoinesjr

**Comment by akoinesjr** [comment]
Thanks @cmckni3 !

**Pull request merged**
